const products = [
  {
    id: "job-house",
    name: "House Blend",
    description: "Our signature blend with notes of caramel and toasted nuts. Carefully crafted from beans sourced across Central and South America, this medium roast delivers a perfectly balanced cup with sweet caramel notes, subtle nuttiness, and a smooth, satisfying finish.",
    image: "/images/joba images/img1.jpeg",
    roast: "Medium",
    origin: "Central & South America",
  },
  {
    id: "job-dark-roast",
    name: "Dark Roast Reserve",
    description: "Bold and intense with deep chocolate and smoky notes. Full-bodied dark roast for those who love a strong, rich coffee. Perfect for espresso or a powerful morning brew.",
    image: "/images/joba images/img2.jpeg",
    roast: "Dark",
    origin: "Multiple Origins",
  },
  {
    id: "job-rwanda",
    name: "Rwandan Sunrise",
    description: "Bright and floral with notes of jasmine and citrus. Medium roast, perfect for filter brewing. Sourced from single-origin Rwandan farms at high altitudes, this coffee delivers a vibrant cup with sweet berry undertones and a clean finish.",
    image: "/images/joba images/img3.jpeg",
    roast: "Medium",
    origin: "Rwanda",
  },
  {
    id: "job-decaf",
    name: "Decaf Delight",
    description: "All the flavor, none of the caffeine. Swiss water processed to preserve the natural taste. Smooth, balanced, and perfect for evening enjoyment.",
    image: "/images/joba images/img4.jpeg",
    roast: "Medium",
    origin: "Multiple Origins",
  },
  {
    id: "job-colombia",
    name: "Colombian Classic",
    description: "Balanced and chocolatey with a smooth finish. Great as espresso or drip. This medium-dark roast showcases the best of Colombian coffee with rich chocolate notes, subtle caramel sweetness, and a velvety body that makes every cup memorable.",
    image: "/images/joba images/img5.jpeg",
    roast: "Medium-Dark",
    origin: "Colombia",
  },
  {
    id: "job-espresso",
    name: "Espresso Blend",
    description: "Perfect for espresso with rich crema and bold flavor. Specially crafted to deliver a smooth, balanced shot with notes of dark chocolate and caramel.",
    image: "/images/joba images/img6.jpeg",
    roast: "Dark",
    origin: "Blend",
  },
  {
    id: "job-single-origin",
    name: "Single Origin",
    description: "Exclusive single-origin beans with unique terroir. Each batch showcases the distinct characteristics of its origin, from bright acidity to deep, complex flavors.",
    image: "/images/joba images/img7.jpeg",
    roast: "Light-Medium",
    origin: "Single Origin",
  },
  {
    id: "job-morning",
    name: "Morning Blend",
    description: "Smooth and energizing, perfect start to your day. This balanced blend delivers consistent flavor with a clean finish that pairs perfectly with breakfast.",
    image: "/images/joba images/img8.jpeg",
    roast: "Medium",
    origin: "Blend",
  },
  {
    id: "job-evening",
    name: "Evening Blend",
    description: "Mellow and comforting, ideal for relaxing moments. A smooth, low-acidity blend perfect for afternoon or evening enjoyment.",
    image: "/images/joba images/img9.jpeg",
    roast: "Medium",
    origin: "Blend",
  },
  {
    id: "job-premium",
    name: "Premium Reserve",
    description: "Our finest selection of carefully curated beans. Limited availability with exceptional quality and unique flavor profiles.",
    image: "/images/joba images/img10.jpeg",
    roast: "Light-Medium",
    origin: "Premium Selection",
  },
  {
    id: "job-specialty",
    name: "Specialty Blend",
    description: "A unique combination of rare beans creating a distinctive flavor profile. Complex notes with a memorable finish.",
    image: "/images/joba images/img11.jpeg",
    roast: "Medium",
    origin: "Specialty Blend",
  },
  {
    id: "job-classic",
    name: "Classic Roast",
    description: "Traditional roasting methods meet modern quality standards. A timeless favorite with consistent, reliable flavor.",
    image: "/images/joba images/img12.jpeg",
    roast: "Medium-Dark",
    origin: "Traditional Blend",
  },
  {
    id: "job-artisan",
    name: "Artisan Collection",
    description: "Handcrafted in small batches with meticulous attention to detail. Each bag represents our commitment to excellence.",
    image: "/images/joba images/img13.jpeg",
    roast: "Varies",
    origin: "Artisan Selection",
  },
  {
    id: "job-signature",
    name: "Signature Series",
    description: "Our most popular collection, representing the essence of Zeytun Restaurant. Perfectly balanced for everyday enjoyment.",
    image: "/images/joba images/img14.jpeg",
    roast: "Medium",
    origin: "Signature Blend",
  },
];

export default products;
